<header>
    <h1><?= $title ?></h1>
    <br>
    <table border="5">
        <tr>
            <td>Datum vytvoření</td>
            <td>
                <?php
                if ($_date !== '0000-00-00')
                {
                echo ( DateUtils::prettyDate($_date) );
                }
                ?>
            </td>
        </tr>
        <tr>
            <td>Datum ukončení</td>
            <td>
                <?php
                if ($_end_date !== '0000-00-00')
                {
                    echo ( DateUtils::prettyDate($_end_date) );
                }
                ?>
            </td>
        </tr>
        <tr>
            <td>Priorita</td>
            <td>
                <?= $_priority ?>
            </td>
        </tr>
        <tr>
            <td>Přiřazen</td>
            <td>
                <?= $_assignee['name'] ?>
            </td>
        </tr>
        <tr>
            <td>Zadavatel</td>
            <td>
                <?= $_create['name'] ?>
            </td>
        </tr>
    </table>


</header>
<section>
    <?= $_content ?>
    <?php if ($admin) : ?>
    <br>
    <a href="editorTask/<?= $url ?>">Editovat</a>
    <?php endif ?>
    <br>
    <div class="ui star rating" data-rating="3"></div>
    <div class="ui mini star rating"></div>
    <div class="ui tiny star rating"></div>
    <div class="ui small star rating"></div>
    <div class="ui star rating"></div>
    <div class="ui large star rating"></div>
    <div class="ui huge star rating"></div>
    <div class="ui massive star rating"></div>
</section>